name: Publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Docker image to GitHub Container Registry
    strategy:
      matrix:
        platform:
          - aarch64
          - amd64
          - armv7
        include:
          - platform: aarch64
            build_from: ghcr.io/hassio-addons/debian-base/aarch64:7.1.0
          - platform: amd64
            build_from: ghcr.io/hassio-addons/debian-base/amd64:7.1.0
          - platform: armv7
            build_from: ghcr.io/hassio-addons/debian-base/armv7:7.1.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./rtorrent
          file: ./rtorrent/Dockerfile
          push: true
          tags: ghcr.io/selfish/ha-rtorrent-addon:${{ matrix.platform }}-latest
          platforms: linux/${{ matrix.platform }}
          args: BUILD_FROM=${{ matrix.build_from }}
